### PR TITLE
fetching tutor data of logged in tutor,

### PR DESCRIPTION
**Pull request by Kremifany**
fetching tutor data of logged in tutor
## Requirements
User with  role tutor must be registered or logged in 

_What this code should do_
update and Create tutor must proceed smooth

## Notes
all console.log's will be removed after adding toaster messages

_Any additional info_

## Test Steps
-Create or Login as a tutor,
-update some or all the fields

_Instructions on how to test the changes_

## UI/UX Outcome
tutor profile must show updated fields 
_Attach a screenshot here_

image

### CODE REVIEW

**Comment by oxangyal** [comment]
Pls align avatar and name, email, the avatar should be pushed up and be at the same level as name, reduce the size of About align vertically with other fields: experience, math and ect.

**Review by IrynaKolh — APPROVED** [review]
LGTM

**Comment by Kremifany** [comment]
image

**Review by mynewyear — APPROVED** [review]
LGTM

**Pull request merged**
